- core/.projen/deps.json
- core/.projenrc.js
- core/package.json
- core/src/ec2-ssm-role.ts
- core/test/ec2-ssm-role.test.ts
- core/yarn.lock
add a new CDK Construct Ec2SsmRole which extends iam.Role to provide a Role with AmazonSSMManagedInstanceCore managed policy
> add Ec2SsmRole

- README.md
Hi,
This PR quickly adds the reference arch. from the live documentation into the main project's readme.
> docs: include ref arch in main readme

- doc/content/solutions/data-warehouse.md
fix the link from DWH solution to AWS Lambda code for Amazon Redshift Data API
> fix link for DWH solution code

- core/.projen/tasks.json
- core/.projenrc.js
- core/src/data-generator.ts
- core/src/synchronous-athena-query.ts
Since there is no dependency yet in those lambda, there is no need for esbuild and we can let projen build the js as well as packaging it automatically.
tested using https://github.com/flochaz/test-aws-analytics-reference-architecture 
```
npm install && npm run cdk synth
```
> Fix lambda bundling

- core/API.md
- core/src/data-lake-catalog.ts
- core/src/data-lake-storage.ts
- core/src/index.ts
- core/src/integ.default.ts
- core/test/data-lake-catalog.test.ts
Description of changes: add a DataLakeCatalog Construct with AWS Glue Database for Raw, Clean and Transform layers
> feat: add data lake catalog construct

- refarch/aws-native/streaming/stream-processing/pom.xml
- Update log4j version to avoid CVE-2021-44228
> fix: bump to log4j 2.16 to avoid vulnerability

- core/src/db-schema-manager/resources/flyway-lambda/build.gradle
- Update log4j version to avoid CVE-2021-44228
- Update mysql-connector-java to avoid CVE-2019-2692
> fix: log4j version in ref analytics flyway

- core/.projen/deps.json
- core/.projen/tasks.json
- core/API.md
- core/README.md
- core/package.json
- core/yarn.lock
Description of changes: change the link to CDK "how to install" from latest (which is now pointing to v2) to v1
> chore: update doc with the right CDK version link

- core/API.md
- core/src/example.ts
Description of changes: This change Imporve the documentation by adding the ignore tag for TypeDoc to not include example.ts in API.md and not have it in construct hub
> fix: exclude example.ts from documentation

- core/src/emr-eks-platform/emr-eks-cluster.ts
Description of changes: Fix the version of k8s autoscaler that is deployed. The newer version cause the autoscaler deployment to fail 
> fix: fix an issue causing k8s autoscaler to fail deploying

- core/src/data-generator/batch-replayer.ts
Description of changes: reduce the memory used by the batchReplayer to match default Lambda limits for newly created accounts
> fix: reduce lambda memory for batchreplayer

- core/.projen/tasks.json
- core/.projenrc.js
- core/src/db-schema-manager/flyway-runner.ts
- core/src/db-schema-manager/resources/flyway-lambda/.gitignore
- core/test/e2e/db-schema-manager.test.ts
Fix #328 
* Build jar in src before moving files to lib
* Ignore it in git
* Add retry in test to delete the stack properly
This enable to 
* have the jar available for jest test
* have a working teardown
> fix: db-shema-manager e2e test fix working around stack deletion issue

- core/API.md
- core/src/integ.default.ts
- core/src/lf-s3-location.ts
- core/test/e2e/lf-s3-location.test.ts
- core/test/unit/cdk-nag/nag-lf-s3-location.test.ts
- core/test/unit/lf-s3-location.test.ts
Issue #, if available: #361
Description of changes:  fix the permissions for the LakeFormationS3Location so it supports S3 buckets and KMS keys in a different account
> fix: lf s3 location

- core/API.md
- core/src/glue-default-role.ts
- core/src/glue-demo-role.ts
- core/src/index.ts
- core/test/e2e/glue-demo-role.test.ts
- core/test/unit/cdk-nag/nag-glue-demo-role.test.ts
- core/test/unit/glue-demo-role.test.ts
Description of changes: fix permissions on GlueDefaultRole and rename to GlueDemoRole
> fix: glue default role kms permissions

- core/src/data-mesh/central-governance.ts
Issue #438, if available:
Description of changes: Add custom identifier to `DomainSecret` to enable multiple data domains to be registered.
> fix: Add domain specific identifier to domain secret

- core/src/data-mesh/central-governance.ts
Issue #440, if available:
Description of changes: Fix typo that caused ill formed interpolation in construct id.
> fix: typo in construct name

- core/src/data-mesh/central-governance.ts
Issue #442, if available:
Description of changes: Add data domain account id to `LFS3Location` when registering new data domain.
> fix: add domain account id for LF S3 location construct

- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/test/unit/cdk-nag/nag-notebook-platform.test.ts
Description of changes: The current default IAM appended to the execution role is not enough to access the pod template. This PR append a wild card to the policy to access the pod template bucket.
> fix: IAM permission for execution role to access pod template

- core/src/singleton-kms-key.ts
Description of changes: Remove unused KMS key alias.
> fix: remove unused KMS alias for singleton kms key

- core/API.md
- core/src/athena-demo-setup.ts
- core/src/index.ts
- core/test/e2e/athena-demo-setup.test.ts
- core/test/e2e/data-domain.test.ts
- core/test/unit/athena-demo-setup.test.ts
- core/test/unit/cdk-nag/nag-athena-demo-setup.test.ts
Description of changes: add a parameter to customize the Athena workgroup setup. The name is used for both the Athena workgroup and the S3 bucket for storing results. It allows for multiple AthenaDemoSetup to be provisioned into one single account. 
> fix: add parameter to customize athena workgroup setup

- core/src/emr-eks-platform/emr-eks-cluster-helpers.ts
- core/src/emr-eks-platform/emr-eks-cluster.ts
- Add explicit dependency between the VC and the namespace to avoid race condition during delete where namespace is deleted before the VC
- Add time out the deploy of cert-manager as suggested in [here](https://github.com/cert-manager/cert-manager/issues/4646)
> fix: add fix for cert-manager and dep for VC

- core/.projen/deps.json
- core/.projenrc.js
- core/package.json
This fix optimize the package size of the dist by removing the kubectl v1.22 lambda layer that should be important and installed by the user.
> fix: remove kubctl v1.22 layer from dep

- core/src/docker-builder/docker-build.ts
- core/test/unit/cdk-nag/nag-docker-build.test.ts
Description of changes: The EmrEksImage publisher construct create an S3 bucket based on the stackname. If the stackname has capital letters the deployment will fail. This change make sure to sanitize the Stack Name before passing it as a name to S3 construct.
> fix: sanitize stackname for emreksimage builder

- core/README.md
The current version of this demo needs aws-cdk-lib==2.51.0 otherwise will throw the following errors during installation:
```
ERROR: aws-cdk-aws-redshift-alpha 2.51.0a0 has requirement aws-cdk-lib<3.0.0,>=2.51.0, but you'll have aws-cdk-lib 2.27.0 which is incompatible.
ERROR: aws-cdk-aws-glue-alpha 2.51.0a0 has requirement aws-cdk-lib<3.0.0,>=2.51.0, but you'll have aws-cdk-lib 2.27.0 which is incompatible.
ERROR: aws-analytics-reference-architecture 2.8.4 has requirement aws-cdk-lib==2.51.0, but you'll have aws-cdk-lib 2.27.0 which is incompatible.
```
> fix: current version needs aws-cdk-lib==2.51.0

- core/README.md
> fix: use AWS_REGION variable for CDK bootstrapping

- examples/emr-eks-app/README.md
- examples/emr-eks-app/lib/emr-eks-app-stack.ts
- examples/emr-eks-app/package.json
Description of changes: fix the IAM permissions of the EMR on EKS job execution role in the EMR on EKS example. Adds CloudWatch CreateLogGroup permission
> fix: update EMR on EKS job execution role permissions in the example

- examples/emr-eks-app/lib/emr-eks-app-stack.ts
- examples/emr-eks-app/package.json
Description of changes: This fix to the example add the k8s kubectl library part of the `package.json`
> fix: add k8s v1_22 layer

- core/src/ara-bucket.ts
- core/test/e2e/data-domain.test.ts
Description of changes: fix the circular dependency error when using bucket policy to manage permissions for S3 access logs
> fix: check s3 access log permissions configuration is correct

- refarch/README.md
- refarch/aws-native/cdk.json
- refarch/aws-native/setup.py
Description of changes: upgrade ARA version to 2.9.11 in the AWS native refarch to be compatible with new S3 default configuration
> fix: upgrade ARA library version in the AWS native refarch

- core/src/data-generator/resources/lambdas/write-in-batch/write-in-batch.py
Description of changes: Batch replay fails when using s3_params with this error:
{
"errorMessage": "'table_name'",
"errorType": "KeyError",
"requestId": "5a0f8b3f-46a4-492a-a497-e5c95431a6e5",
"stackTrace": [
"  File \"/var/task/write-in-batch.py\", line 314, in handler\n    write_all(df_split, target_params)\n",
"  File \"/var/task/write-in-batch.py\", line 214, in write_all\n    log.info(f\"## Writing concatenated data to the {params['table_name']} table in {target}>\")\n"
]
}
Adding table_name to target_params['s3'] fixes the issue.
> fix: write in batch lambda when using s3 requires table name

- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/src/emr-eks-platform/vpc-helper.ts
- core/test/unit/emr-eks-platform/emr-eks-cluster.test.ts
Description of changes: This change add the ability to control the cidr of the VPC or to provide your own VPC to deploy the EKS cluster.
> feat: Add custom vpc and cidr field to emreks construct

- core/API.md
- core/src/data-generator/batch-replayer-helpers.ts
- core/src/data-generator/batch-replayer.ts
- core/src/data-generator/index.ts
- core/src/index.ts
- core/test/e2e/batch-replayer.test.ts
- core/test/unit/cdk-nag/nag-batch-replayer.test.ts
- core/test/unit/data-generator/batch-replayer.test.ts
- core/yarn.lock
Description of changes: The use of Interface with the name starting with `I` should be excluded because JSII convert it to Python Protocols and resource references cannot be used in Protocols (only values resolved at compile time). The `IS3Sink` is now a `S3Sink` which is considered as a struct.
> fix: change BatchReplayer props to solve JSII conversion issue in Python with IS3Sink

- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster.ts
When there is already a service role for emr containers the cdk deploy fail, we add a flag to allow the user not to create the service linked role.
> fix: add flag for service linked role
