- core/API.md
- core/src/example.ts
- core/test/example.test.ts
Add more guidelines in the Example Construct to help new contributors
> feat: adding contributing guidelines example

- core/API.md
- core/src/example.ts
- core/test/example.test.ts
> refactoring dev convention

- .mergify.yml
Fixes #
automatic merge of dependabot when build is successful
automatic merge of approved PR when build is successful
> adding mergify

- core/.projenrc.js
Description of changes: change the name of pypi dist
> ci: changing pypi dist name

- core/API.md
- core/src/data-generator.ts
- core/src/dataset.ts
- core/src/datasets/retail-customer-address.ts
- core/src/datasets/retail-customer.ts
- core/src/datasets/retail-item.ts
- core/src/datasets/retail-promo.ts
- core/src/datasets/retail-store-sale.ts
- core/src/datasets/retail-store.ts
- core/src/datasets/retail-warehouse.ts
- core/src/datasets/retail-web-sale.ts
- core/src/singleton-glue-database.ts
- core/test/dataset.test.ts
- core/test/singleton-glue-database.test.ts
Description of changes: fix data multiple generator failures
> fix: data generator

- .github/workflows/release.yml
Description of changes: fix pypi release workflow
> fix: pypi workflows

- core/src/common/context-options.ts
- core/src/common/tracked-construct.ts
- core/test/tracked-construct.test.ts
- refarch/aws-native/cdk.json
- refarch/aws-native/common/common_cdk/data_lake.py
- refarch/aws-native/setup.py
- Track ref arch deployments
- Add tracking code capability
> Add deployment trackers to evaluate adoption

- core/.projen/tasks.json
Description of changes: fix the build process
> fix: build process

- .github/workflows/release.yml
> fix: set java 11 in release action

- core/README.md
* Fix the link from construct hub to point to the latest version
> chore: fix link in core getting started

- core/LICENSE
Description of changes: update the license file with year 2022 to fix the release process 
> fix: license year

- README.md
- core/README.md
- refarch/README.md
- refarch/aws-native/setup.py
Description of changes: update the main readme with links to latest versions of docs
> chore: readme update

- core/API.md
- core/src/data-generator/resources/lambdas/write-in-batch/write-in-batch.py
- core/src/datasets/prepared-dataset.ts
- core/src/integ.default.ts
Description of changes: remove row index from batchreplayer writes
> fix: batchreplayer write

- .github/workflows/pull-request-lint.yml
update the pull-request-lint action to accept to accept PR with `doc` in title
> fix: Update pull-request-lint.yml

- .github/workflows/pull-request-lint.yml
- CONTRIB_FAQ.md
Description of changes: 
Adding a step to install `glob` to allow local build
> fix: Update the CONTRIB_FAQ

- core/.projen/tasks.json
- core/.projenrc.js
Description of changes: change the build process in projen to fix issue related to db-schema-manager jar copy/delete
> fix: projen build process

- core/API.md
- core/package.json
- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/yarn.lock
#351
Description of changes: Add a parameter in the emr-eks props take the autoscaler for EKS
> fix: add parameter for autoscaler on emr-eks-cluster.ts

- core/README.md
Description of changes: updates versions and code snippets in the getting started documentation for the core library
> fix: update core getting started doc

- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/src/notebook-platform/notebook-managed-endpoint.ts
- core/src/notebook-platform/notebook-platform.ts
- core/test/unit/cdk-nag/nag-notebook-platform.test.ts
- core/test/unit/notebook-platform/notebook-platform.test.ts
Description of changes: Made the endpoint name mandatory for managedendpoint to resolve issues for scoping its execution role
> fix: Fix scoping condition for execution role

- core/src/athena-demo-setup.ts
- core/test/unit/athena-demo-setup.test.ts
Description of changes: Set requester pay to true for athena demo workgroup
> fix: add the request pay option to workgroup

- core/src/data-mesh/data-domain.ts
Description of changes: Add data domain name to domain-config secret.
> feat: add data domain name to domain-config secret

- core/src/data-mesh/data-domain-tbac-workflow.ts
Description of changes: Update tbac state machine to support consumer sharing workflow.
> fix: update tbac state machine to support consumer workflow

- core/src/data-mesh/data-domain-crawler.ts
- core/test/unit/data-mesh/data-domain-crawler.test.ts
Description of changes: Refactor emitting crawler event to central gov. account. Send periodic event until crawler is finished.
> feat: refactor crawler event to central

- refarch/README.md
- refarch/aws-native/dataviz/dataviz_redshift_cdk/app.py
- refarch/aws-native/dataviz/dataviz_redshift_cdk/cdk.json
- refarch/aws-native/dataviz/dataviz_redshift_cdk/dataviz_redshift/dataviz_redshift_stack.py
- refarch/aws-native/dataviz/dataviz_redshift_cdk/setup.py
Description of changes: fix the redshift dataviz stack after upgrade to cdk v2
> fix: [AWS native ref arch] upgrade redshift dataviz stack

- core/src/data-mesh/data-domain-nrac-workflow.ts
Description of changes: Update NRAC state machine to reflect change in LF+RAM services. After initial RAM share to another account, every subsequent RAM is automatically accepted.
> fix: update NRAC state machine to reflect service change

- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/yarn.lock
This PR changes the following:
- Add EMR 6.8
- Refactor the RBAC role for EMR on EKS
- Remove ERM configuration override validation check
> fix: improvements in emr-eks

- core/src/data-generator/batch-replayer.ts
Issue #, if available: #400 
- update BatchReplayer sinkObjectKey parameter to reflect it's default value when it's not set 
> fix: fix batch replayer parameters

- .gitignore
- core/API.md
- core/src/common/cdk-deployer-build.ts
- core/src/common/cdk-deployer.ts
- core/src/common/resources/lambdas/cdk-deployer/reportbuild.js
- core/src/common/resources/lambdas/cdk-deployer/startbuild.js
- core/src/index.ts
- core/src/integ.default.ts
- core/src/lake-formation/lake-formation-admin.ts
- core/src/utils.ts
- core/test/e2e/cdk-deployer.test.ts
- core/test/e2e/data-domain.test.ts
- core/test/e2e/utils.ts
- core/test/unit/cdk-deployer.test.ts
- core/test/unit/cdk-nag/nag-cdk-deployer.test.ts
Description of changes: Add a construct stack to trigger CDK application deployment from github
> chore(deploy): add click to deploy

- core/API.md
- core/src/common/cdk-deployer.ts
- core/test/e2e/cdk-deployer.test.ts
Description of changes: add branch support for CdkDeployer
> fix: add branch support for CdkDeployer

- core/API.md
- core/src/common/cdk-deployer-build.ts
- core/src/common/cdk-deployer.ts
- core/src/index.ts
- core/src/integ.default.ts
- core/test/e2e/cdk-deployer.test.ts
- core/test/unit/cdk-deployer.test.ts
- core/test/unit/cdk-nag/nag-cdk-deployer.test.ts
> chore(click2deploy): add workshop studio support

- core/API.md
- core/src/common/cdk-deployer-build.ts
- core/src/common/cdk-deployer.ts
- core/test/unit/cdk-deployer.test.ts
> chore(cdkDeployer): Add custom build spec option

- examples/emr-eks-app/lib/emr-eks-app-stack.ts
- examples/emr-eks-app/package.json
> doc: update with example with v2.6.0

- examples/emr-eks-app/package.json
Description of changes: This upgrade the typescript version in the example
> doc: update typescript version to example

- core/src/emr-eks-platform/resources/k8s/rbac/emr-containers-role.json
Issue #, if available: This PR change the RBAC to support k8s 1.22
> feat: Update RBAC for k8s 1.22

- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/test/unit/emr-eks-platform/emr-eks-cluster.test.ts
> feat: bump to k8s v1.22

- core/src/emr-eks-platform/resources/k8s/emr-eks-config/critical.json
- core/test/unit/cdk-nag/nag-docker-build.test.ts
> fix: fix in emr eks critical pod def

- refarch/README.md
Description of changes: fix documentation for AWS native refarch getting started. Add the stack name to deploy
> fix: getting started ref arch deployment doc

- refarch/aws-native/cdk.context.json
- refarch/aws-native/dataviz/dataviz_cdk/qs_athena_analysis.py
Description of changes: fix quicksight analysis ID to allow for deletion
> fix: quicksight analysis custom resource

- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster.ts
> fix: add emr 6.10

- core/src/data-mesh/central-governance.ts
- core/src/data-mesh/data-domain-nrac-workflow.ts
Description of changes: Fix how RAM shares are handled in Data Domain for NRAC. Add retry in Central Gov. to handle parallel crawler executions when registering multiple data products at once.
> fix: data mesh RAM shares

- .github/workflows/pull-request-lint.yml
> feat: add a test type to linter tittle

- .gitignore
- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster.ts
- examples/emr-eks-app-python/app.py
- examples/emr-eks-app-python/ara_py/ara_py_stack.py
- examples/emr-eks-app-python/cdk.json
- examples/emr-eks-app-python/requirements.txt
- examples/emr-eks-app/package.json
Description of changes: solves #633 , #632 , #631 
> fix: EMR EKS bucket config

- refarch/aws-native/setup.py
> fix: pin the ara version in ref arch

- poc/cdk.json
- poc/poc/poc_stack.py
> doc: poc guidance

- examples/emr-eks-app-python/ara_py/ara_py_stack.py
- examples/emr-eks-app-python/requirements.txt
- poc/poc/poc_stack.py
- poc/requirements.txt
> doc: bump layer to k8s 1.25

- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/critical-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/notebook-driver-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/notebook-executor-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/shared-driver-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/shared-executor-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/tooling-provisioner.yml
- core/src/singleton-launch-template.ts
> fix: improvement for managed nodegroup and karpenter provisioner

- core/API.md
- core/src/data-generator/batch-replayer-helpers.ts
- core/src/data-generator/batch-replayer.ts
- core/src/data-generator/index.ts
- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/critical-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/notebook-driver-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/notebook-executor-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/shared-driver-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/shared-executor-provisioner.yml
- core/src/emr-eks-platform/resources/k8s/karpenter-provisioner-config/tooling-provisioner.yml
- core/src/index.ts
- core/src/singleton-launch-template.ts
- core/test/e2e/batch-replayer.test.ts
- core/test/unit/cdk-nag/nag-batch-replayer.test.ts
- core/test/unit/data-generator/batch-replayer.test.ts
- core/yarn.lock
> fix: bump cdk

- .github/workflows/release.yml
Description of changes: fix the node version for release
> fix node version release action

- .github/workflows/release.yml
- examples/emr-eks-app-python/requirements.txt
- examples/emr-eks-app/package.json
- poc/requirements.txt
Description of changes: bump cdk version in examples
> chore: bump cdk and ara version in examples

- doc/content/index.md
- doc/mkdocs.yml
> doc: add deprecation on main doc

- .github/workflows/build.yml
- .github/workflows/release.yml
> fix: the release pipeline

- core/src/emr-eks-platform/resources/k8s/iam-policy-alb.json
> fix: fix alb policy

- core/API.md
- core/src/emr-eks-platform/emr-eks-cluster-helpers.ts
- core/src/emr-eks-platform/emr-eks-cluster.ts
- core/test/unit/cdk-nag/nag-emr-eks.test.ts
- core/test/unit/cdk-nag/nag-notebook-platform.test.ts
- core/test/unit/emr-eks-platform/emr-eks-cluster.test.ts
Issue #705
1. Add AlbController as config parameter
2. Add Emr latest version
> fix: introduce built in ALB, increase EMR version

- .github/workflows/build.yml
- .github/workflows/release.yml
> ci: bump node for build build.yml
